//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCITC.MES.IP.AAA.AppService.Entity
{
    using System.Runtime.Serialization;
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthPropCodeValue", Namespace="http://schemas.datacontract.org/2004/07/PCITC.MES.IP.AAA.AppService.Entity")]
    public partial class AuthPropCodeValue : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodeField;
        
        private string ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Permission", Namespace="http://schemas.datacontract.org/2004/07/PCITC.MES.IP.AAA.AppService.Entity")]
    public partial class Permission : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AuthClassCodeField;
        
        private string AuthClassNameField;
        
        private string OperationCodeField;
        
        private string OperationNameField;
        
        private PCITC.MES.IP.AAA.AppService.Entity.AuthPropertyValue[] PropertiesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthClassCode
        {
            get
            {
                return this.AuthClassCodeField;
            }
            set
            {
                this.AuthClassCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthClassName
        {
            get
            {
                return this.AuthClassNameField;
            }
            set
            {
                this.AuthClassNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationCode
        {
            get
            {
                return this.OperationCodeField;
            }
            set
            {
                this.OperationCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationName
        {
            get
            {
                return this.OperationNameField;
            }
            set
            {
                this.OperationNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PCITC.MES.IP.AAA.AppService.Entity.AuthPropertyValue[] Properties
        {
            get
            {
                return this.PropertiesField;
            }
            set
            {
                this.PropertiesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthPropertyValue", Namespace="http://schemas.datacontract.org/2004/07/PCITC.MES.IP.AAA.AppService.Entity")]
    public partial class AuthPropertyValue : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private PCITC.MES.IP.AAA.AppService.Entity.AuthProperty AuthPropertyField;
        
        private string NameField;
        
        private System.Nullable<int> OrderIdField;
        
        private System.Nullable<long> ParentIdField;
        
        private long PropertyValueIdField;
        
        private string SourceIdField;
        
        private string ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PCITC.MES.IP.AAA.AppService.Entity.AuthProperty AuthProperty
        {
            get
            {
                return this.AuthPropertyField;
            }
            set
            {
                this.AuthPropertyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ParentId
        {
            get
            {
                return this.ParentIdField;
            }
            set
            {
                this.ParentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PropertyValueId
        {
            get
            {
                return this.PropertyValueIdField;
            }
            set
            {
                this.PropertyValueIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceId
        {
            get
            {
                return this.SourceIdField;
            }
            set
            {
                this.SourceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthProperty", Namespace="http://schemas.datacontract.org/2004/07/PCITC.MES.IP.AAA.AppService.Entity")]
    public partial class AuthProperty : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NameField;
        
        private string PropertyCodeField;
        
        private long PropertyIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyCode
        {
            get
            {
                return this.PropertyCodeField;
            }
            set
            {
                this.PropertyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PropertyId
        {
            get
            {
                return this.PropertyIdField;
            }
            set
            {
                this.PropertyIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthObject", Namespace="http://schemas.datacontract.org/2004/07/PCITC.MES.IP.AAA.AppService.Entity")]
    public partial class AuthObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private PCITC.MES.IP.AAA.AppService.Entity.AuthClass AuthClassField;
        
        private long ObjectIdField;
        
        private PCITC.MES.IP.AAA.AppService.Entity.AuthPropertyValue[] PropertyValuesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PCITC.MES.IP.AAA.AppService.Entity.AuthClass AuthClass
        {
            get
            {
                return this.AuthClassField;
            }
            set
            {
                this.AuthClassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ObjectId
        {
            get
            {
                return this.ObjectIdField;
            }
            set
            {
                this.ObjectIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PCITC.MES.IP.AAA.AppService.Entity.AuthPropertyValue[] PropertyValues
        {
            get
            {
                return this.PropertyValuesField;
            }
            set
            {
                this.PropertyValuesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthClass", Namespace="http://schemas.datacontract.org/2004/07/PCITC.MES.IP.AAA.AppService.Entity")]
    public partial class AuthClass : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private PCITC.MES.IP.AAA.AppService.Entity.Application ApplicationField;
        
        private PCITC.MES.IP.AAA.AppService.Entity.AuthProperty[] AuthPropertiesField;
        
        private long ClassIdField;
        
        private string CodeField;
        
        private string DescField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PCITC.MES.IP.AAA.AppService.Entity.Application Application
        {
            get
            {
                return this.ApplicationField;
            }
            set
            {
                this.ApplicationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PCITC.MES.IP.AAA.AppService.Entity.AuthProperty[] AuthProperties
        {
            get
            {
                return this.AuthPropertiesField;
            }
            set
            {
                this.AuthPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ClassId
        {
            get
            {
                return this.ClassIdField;
            }
            set
            {
                this.ClassIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Desc
        {
            get
            {
                return this.DescField;
            }
            set
            {
                this.DescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Application", Namespace="http://schemas.datacontract.org/2004/07/PCITC.MES.IP.AAA.AppService.Entity")]
    public partial class Application : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AppCodeField;
        
        private long AppIdField;
        
        private string AppNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppCode
        {
            get
            {
                return this.AppCodeField;
            }
            set
            {
                this.AppCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AppId
        {
            get
            {
                return this.AppIdField;
            }
            set
            {
                this.AppIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppName
        {
            get
            {
                return this.AppNameField;
            }
            set
            {
                this.AppNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Page", Namespace="http://schemas.datacontract.org/2004/07/PCITC.MES.IP.AAA.AppService.Entity")]
    public partial class Page : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodeField;
        
        private string NameField;
        
        private long PageIdField;
        
        private PCITC.MES.IP.AAA.AppService.Entity.PageResource[] PageResourcesField;
        
        private long ParentIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PageId
        {
            get
            {
                return this.PageIdField;
            }
            set
            {
                this.PageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PCITC.MES.IP.AAA.AppService.Entity.PageResource[] PageResources
        {
            get
            {
                return this.PageResourcesField;
            }
            set
            {
                this.PageResourcesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ParentId
        {
            get
            {
                return this.ParentIdField;
            }
            set
            {
                this.ParentIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PageResource", Namespace="http://schemas.datacontract.org/2004/07/PCITC.MES.IP.AAA.AppService.Entity")]
    public partial class PageResource : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ControlIdField;
        
        private System.Nullable<int> OrderIdField;
        
        private long ResIdField;
        
        private string TextField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ControlId
        {
            get
            {
                return this.ControlIdField;
            }
            set
            {
                this.ControlIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ResId
        {
            get
            {
                return this.ResIdField;
            }
            set
            {
                this.ResIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IAuthorizeService")]
public interface IAuthorizeService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizeService/IsAuthorized", ReplyAction="http://tempuri.org/IAuthorizeService/IsAuthorizedResponse")]
    bool IsAuthorized(string loginName, string authClassCode, string operationCode, PCITC.MES.IP.AAA.AppService.Entity.AuthPropCodeValue[] listPropCodeValue);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizeService/IsAuthorized", ReplyAction="http://tempuri.org/IAuthorizeService/IsAuthorizedResponse")]
    System.Threading.Tasks.Task<bool> IsAuthorizedAsync(string loginName, string authClassCode, string operationCode, PCITC.MES.IP.AAA.AppService.Entity.AuthPropCodeValue[] listPropCodeValue);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizeService/ListPermissionByAuthClassCode", ReplyAction="http://tempuri.org/IAuthorizeService/ListPermissionByAuthClassCodeResponse")]
    PCITC.MES.IP.AAA.AppService.Entity.Permission[] ListPermissionByAuthClassCode(string loginName, string authClassCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizeService/ListPermissionByAuthClassCode", ReplyAction="http://tempuri.org/IAuthorizeService/ListPermissionByAuthClassCodeResponse")]
    System.Threading.Tasks.Task<PCITC.MES.IP.AAA.AppService.Entity.Permission[]> ListPermissionByAuthClassCodeAsync(string loginName, string authClassCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizeService/ListPropertyValuesByCode", ReplyAction="http://tempuri.org/IAuthorizeService/ListPropertyValuesByCodeResponse")]
    PCITC.MES.IP.AAA.AppService.Entity.AuthPropertyValue[] ListPropertyValuesByCode(string propertyCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizeService/ListPropertyValuesByCode", ReplyAction="http://tempuri.org/IAuthorizeService/ListPropertyValuesByCodeResponse")]
    System.Threading.Tasks.Task<PCITC.MES.IP.AAA.AppService.Entity.AuthPropertyValue[]> ListPropertyValuesByCodeAsync(string propertyCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizeService/ListPropertyValue", ReplyAction="http://tempuri.org/IAuthorizeService/ListPropertyValueResponse")]
    PCITC.MES.IP.AAA.AppService.Entity.AuthPropertyValue[] ListPropertyValue(string loginName, string propertyCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizeService/ListPropertyValue", ReplyAction="http://tempuri.org/IAuthorizeService/ListPropertyValueResponse")]
    System.Threading.Tasks.Task<PCITC.MES.IP.AAA.AppService.Entity.AuthPropertyValue[]> ListPropertyValueAsync(string loginName, string propertyCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizeService/ListPropertyValueByClassCode", ReplyAction="http://tempuri.org/IAuthorizeService/ListPropertyValueByClassCodeResponse")]
    PCITC.MES.IP.AAA.AppService.Entity.AuthPropertyValue[] ListPropertyValueByClassCode(string loginName, string authClassCode, string propertyCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizeService/ListPropertyValueByClassCode", ReplyAction="http://tempuri.org/IAuthorizeService/ListPropertyValueByClassCodeResponse")]
    System.Threading.Tasks.Task<PCITC.MES.IP.AAA.AppService.Entity.AuthPropertyValue[]> ListPropertyValueByClassCodeAsync(string loginName, string authClassCode, string propertyCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizeService/ListPropertyValueByOperationCode", ReplyAction="http://tempuri.org/IAuthorizeService/ListPropertyValueByOperationCodeResponse")]
    PCITC.MES.IP.AAA.AppService.Entity.AuthPropertyValue[] ListPropertyValueByOperationCode(string loginName, string authClassCode, string operationCode, string propertyCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizeService/ListPropertyValueByOperationCode", ReplyAction="http://tempuri.org/IAuthorizeService/ListPropertyValueByOperationCodeResponse")]
    System.Threading.Tasks.Task<PCITC.MES.IP.AAA.AppService.Entity.AuthPropertyValue[]> ListPropertyValueByOperationCodeAsync(string loginName, string authClassCode, string operationCode, string propertyCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizeService/Authorize", ReplyAction="http://tempuri.org/IAuthorizeService/AuthorizeResponse")]
    void Authorize(string loginName, string opCode, string propCode, string propValueName, string propValue, string appCode, string token);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizeService/Authorize", ReplyAction="http://tempuri.org/IAuthorizeService/AuthorizeResponse")]
    System.Threading.Tasks.Task AuthorizeAsync(string loginName, string opCode, string propCode, string propValueName, string propValue, string appCode, string token);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizeService/HasAuthorized", ReplyAction="http://tempuri.org/IAuthorizeService/HasAuthorizedResponse")]
    bool HasAuthorized(string loginName, string opCode, string propCode, string propValue, string appCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizeService/HasAuthorized", ReplyAction="http://tempuri.org/IAuthorizeService/HasAuthorizedResponse")]
    System.Threading.Tasks.Task<bool> HasAuthorizedAsync(string loginName, string opCode, string propCode, string propValue, string appCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizeService/ListAuthObjects", ReplyAction="http://tempuri.org/IAuthorizeService/ListAuthObjectsResponse")]
    PCITC.MES.IP.AAA.AppService.Entity.AuthObject[] ListAuthObjects(string loginName, string authClassCode, string opCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizeService/ListAuthObjects", ReplyAction="http://tempuri.org/IAuthorizeService/ListAuthObjectsResponse")]
    System.Threading.Tasks.Task<PCITC.MES.IP.AAA.AppService.Entity.AuthObject[]> ListAuthObjectsAsync(string loginName, string authClassCode, string opCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizeService/ListAuthorizedPropertyValues", ReplyAction="http://tempuri.org/IAuthorizeService/ListAuthorizedPropertyValuesResponse")]
    PCITC.MES.IP.AAA.AppService.Entity.AuthPropertyValue[] ListAuthorizedPropertyValues(string loginName, string appCode, string propertyCode, string opCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizeService/ListAuthorizedPropertyValues", ReplyAction="http://tempuri.org/IAuthorizeService/ListAuthorizedPropertyValuesResponse")]
    System.Threading.Tasks.Task<PCITC.MES.IP.AAA.AppService.Entity.AuthPropertyValue[]> ListAuthorizedPropertyValuesAsync(string loginName, string appCode, string propertyCode, string opCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizeService/ListPageWithResourceByPageId", ReplyAction="http://tempuri.org/IAuthorizeService/ListPageWithResourceByPageIdResponse")]
    PCITC.MES.IP.AAA.AppService.Entity.Page[] ListPageWithResourceByPageId(string loginName, long pageId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizeService/ListPageWithResourceByPageId", ReplyAction="http://tempuri.org/IAuthorizeService/ListPageWithResourceByPageIdResponse")]
    System.Threading.Tasks.Task<PCITC.MES.IP.AAA.AppService.Entity.Page[]> ListPageWithResourceByPageIdAsync(string loginName, long pageId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizeService/HasAuthorizedRole", ReplyAction="http://tempuri.org/IAuthorizeService/HasAuthorizedRoleResponse")]
    bool HasAuthorizedRole(string loginName, string roleCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizeService/HasAuthorizedRole", ReplyAction="http://tempuri.org/IAuthorizeService/HasAuthorizedRoleResponse")]
    System.Threading.Tasks.Task<bool> HasAuthorizedRoleAsync(string loginName, string roleCode);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IAuthorizeServiceChannel : IAuthorizeService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class AuthorizeServiceClient : System.ServiceModel.ClientBase<IAuthorizeService>, IAuthorizeService
{
    
    public AuthorizeServiceClient()
    {
    }
    
    public AuthorizeServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public AuthorizeServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AuthorizeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AuthorizeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool IsAuthorized(string loginName, string authClassCode, string operationCode, PCITC.MES.IP.AAA.AppService.Entity.AuthPropCodeValue[] listPropCodeValue)
    {
        return base.Channel.IsAuthorized(loginName, authClassCode, operationCode, listPropCodeValue);
    }
    
    public System.Threading.Tasks.Task<bool> IsAuthorizedAsync(string loginName, string authClassCode, string operationCode, PCITC.MES.IP.AAA.AppService.Entity.AuthPropCodeValue[] listPropCodeValue)
    {
        return base.Channel.IsAuthorizedAsync(loginName, authClassCode, operationCode, listPropCodeValue);
    }
    
    public PCITC.MES.IP.AAA.AppService.Entity.Permission[] ListPermissionByAuthClassCode(string loginName, string authClassCode)
    {
        return base.Channel.ListPermissionByAuthClassCode(loginName, authClassCode);
    }
    
    public System.Threading.Tasks.Task<PCITC.MES.IP.AAA.AppService.Entity.Permission[]> ListPermissionByAuthClassCodeAsync(string loginName, string authClassCode)
    {
        return base.Channel.ListPermissionByAuthClassCodeAsync(loginName, authClassCode);
    }
    
    public PCITC.MES.IP.AAA.AppService.Entity.AuthPropertyValue[] ListPropertyValuesByCode(string propertyCode)
    {
        return base.Channel.ListPropertyValuesByCode(propertyCode);
    }
    
    public System.Threading.Tasks.Task<PCITC.MES.IP.AAA.AppService.Entity.AuthPropertyValue[]> ListPropertyValuesByCodeAsync(string propertyCode)
    {
        return base.Channel.ListPropertyValuesByCodeAsync(propertyCode);
    }
    
    public PCITC.MES.IP.AAA.AppService.Entity.AuthPropertyValue[] ListPropertyValue(string loginName, string propertyCode)
    {
        return base.Channel.ListPropertyValue(loginName, propertyCode);
    }
    
    public System.Threading.Tasks.Task<PCITC.MES.IP.AAA.AppService.Entity.AuthPropertyValue[]> ListPropertyValueAsync(string loginName, string propertyCode)
    {
        return base.Channel.ListPropertyValueAsync(loginName, propertyCode);
    }
    
    public PCITC.MES.IP.AAA.AppService.Entity.AuthPropertyValue[] ListPropertyValueByClassCode(string loginName, string authClassCode, string propertyCode)
    {
        return base.Channel.ListPropertyValueByClassCode(loginName, authClassCode, propertyCode);
    }
    
    public System.Threading.Tasks.Task<PCITC.MES.IP.AAA.AppService.Entity.AuthPropertyValue[]> ListPropertyValueByClassCodeAsync(string loginName, string authClassCode, string propertyCode)
    {
        return base.Channel.ListPropertyValueByClassCodeAsync(loginName, authClassCode, propertyCode);
    }
    
    public PCITC.MES.IP.AAA.AppService.Entity.AuthPropertyValue[] ListPropertyValueByOperationCode(string loginName, string authClassCode, string operationCode, string propertyCode)
    {
        return base.Channel.ListPropertyValueByOperationCode(loginName, authClassCode, operationCode, propertyCode);
    }
    
    public System.Threading.Tasks.Task<PCITC.MES.IP.AAA.AppService.Entity.AuthPropertyValue[]> ListPropertyValueByOperationCodeAsync(string loginName, string authClassCode, string operationCode, string propertyCode)
    {
        return base.Channel.ListPropertyValueByOperationCodeAsync(loginName, authClassCode, operationCode, propertyCode);
    }
    
    public void Authorize(string loginName, string opCode, string propCode, string propValueName, string propValue, string appCode, string token)
    {
        base.Channel.Authorize(loginName, opCode, propCode, propValueName, propValue, appCode, token);
    }
    
    public System.Threading.Tasks.Task AuthorizeAsync(string loginName, string opCode, string propCode, string propValueName, string propValue, string appCode, string token)
    {
        return base.Channel.AuthorizeAsync(loginName, opCode, propCode, propValueName, propValue, appCode, token);
    }
    
    public bool HasAuthorized(string loginName, string opCode, string propCode, string propValue, string appCode)
    {
        return base.Channel.HasAuthorized(loginName, opCode, propCode, propValue, appCode);
    }
    
    public System.Threading.Tasks.Task<bool> HasAuthorizedAsync(string loginName, string opCode, string propCode, string propValue, string appCode)
    {
        return base.Channel.HasAuthorizedAsync(loginName, opCode, propCode, propValue, appCode);
    }
    
    public PCITC.MES.IP.AAA.AppService.Entity.AuthObject[] ListAuthObjects(string loginName, string authClassCode, string opCode)
    {
        return base.Channel.ListAuthObjects(loginName, authClassCode, opCode);
    }
    
    public System.Threading.Tasks.Task<PCITC.MES.IP.AAA.AppService.Entity.AuthObject[]> ListAuthObjectsAsync(string loginName, string authClassCode, string opCode)
    {
        return base.Channel.ListAuthObjectsAsync(loginName, authClassCode, opCode);
    }
    
    public PCITC.MES.IP.AAA.AppService.Entity.AuthPropertyValue[] ListAuthorizedPropertyValues(string loginName, string appCode, string propertyCode, string opCode)
    {
        return base.Channel.ListAuthorizedPropertyValues(loginName, appCode, propertyCode, opCode);
    }
    
    public System.Threading.Tasks.Task<PCITC.MES.IP.AAA.AppService.Entity.AuthPropertyValue[]> ListAuthorizedPropertyValuesAsync(string loginName, string appCode, string propertyCode, string opCode)
    {
        return base.Channel.ListAuthorizedPropertyValuesAsync(loginName, appCode, propertyCode, opCode);
    }
    
    public PCITC.MES.IP.AAA.AppService.Entity.Page[] ListPageWithResourceByPageId(string loginName, long pageId)
    {
        return base.Channel.ListPageWithResourceByPageId(loginName, pageId);
    }
    
    public System.Threading.Tasks.Task<PCITC.MES.IP.AAA.AppService.Entity.Page[]> ListPageWithResourceByPageIdAsync(string loginName, long pageId)
    {
        return base.Channel.ListPageWithResourceByPageIdAsync(loginName, pageId);
    }
    
    public bool HasAuthorizedRole(string loginName, string roleCode)
    {
        return base.Channel.HasAuthorizedRole(loginName, roleCode);
    }
    
    public System.Threading.Tasks.Task<bool> HasAuthorizedRoleAsync(string loginName, string roleCode)
    {
        return base.Channel.HasAuthorizedRoleAsync(loginName, roleCode);
    }
}
