//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCITC.MES.MM.CU.BLL.Entity
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnitShiftTime", Namespace="http://schemas.datacontract.org/2004/07/PCITC.MES.MM.CU.BLL.Entity")]
    public partial class UnitShiftTime : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long InstrDataIdField;
        
        private long MtrlIdField;
        
        private long NodeIdField;
        
        private long[] ObjIdsField;
        
        private long QutyRankIdField;
        
        private System.Nullable<System.DateTime> ShiftBeginTimeField;
        
        private System.Nullable<System.DateTime> ShiftEndTimeField;
        
        private long UnitIdField;
        
        private string UnitNameField;
        
        private long UnitStateRecIdField;
        
        private string UserIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long InstrDataId
        {
            get
            {
                return this.InstrDataIdField;
            }
            set
            {
                this.InstrDataIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MtrlId
        {
            get
            {
                return this.MtrlIdField;
            }
            set
            {
                this.MtrlIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NodeId
        {
            get
            {
                return this.NodeIdField;
            }
            set
            {
                this.NodeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long[] ObjIds
        {
            get
            {
                return this.ObjIdsField;
            }
            set
            {
                this.ObjIdsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long QutyRankId
        {
            get
            {
                return this.QutyRankIdField;
            }
            set
            {
                this.QutyRankIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ShiftBeginTime
        {
            get
            {
                return this.ShiftBeginTimeField;
            }
            set
            {
                this.ShiftBeginTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ShiftEndTime
        {
            get
            {
                return this.ShiftEndTimeField;
            }
            set
            {
                this.ShiftEndTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UnitId
        {
            get
            {
                return this.UnitIdField;
            }
            set
            {
                this.UnitIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitName
        {
            get
            {
                return this.UnitNameField;
            }
            set
            {
                this.UnitNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UnitStateRecId
        {
            get
            {
                return this.UnitStateRecIdField;
            }
            set
            {
                this.UnitStateRecIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InstrumentMeasureRec", Namespace="http://schemas.datacontract.org/2004/07/PCITC.MES.MM.CU.BLL.Entity")]
    public partial class InstrumentMeasureRec : PCITC.MES.MM.CU.BLL.Entity.CommonProp
    {
        
        private System.Nullable<int> AccuInstrFlagField;
        
        private System.Nullable<System.DateTime> BegShiftTimeField;
        
        private System.Nullable<decimal> CoefficientField;
        
        private int DimensionIdField;
        
        private System.Nullable<System.DateTime> EndShiftTimeField;
        
        private string HasChildField;
        
        private long IdField;
        
        private long InitIdField;
        
        private System.Nullable<decimal> InitPreValField;
        
        private System.Nullable<System.DateTime> InitTimeField;
        
        private System.Nullable<decimal> InitValField;
        
        private string InstrAliasField;
        
        private long InstrDataIdField;
        
        private long InstrIdField;
        
        private System.Nullable<decimal> InstrRawValField;
        
        private System.Nullable<int> InstrTagStatField;
        
        private System.Nullable<decimal> InstrVadValField;
        
        private PCITC.MES.MM.CU.BLL.Entity.InstrumentMeasureRec1[] ListSub1Field;
        
        private string MtrlAliasField;
        
        private System.Nullable<long> MtrlIdField;
        
        private System.Nullable<decimal> NetWeightField;
        
        private string NodeAliasField;
        
        private long NodeAreaIdField;
        
        private System.Nullable<long> NodeIdField;
        
        private string OprterField;
        
        private long PNodeAreaIdField;
        
        private System.Nullable<decimal> PreVadValField;
        
        private System.Nullable<long> QutyRankIdField;
        
        private string RankNameField;
        
        private System.Nullable<System.DateTime> ReadTimeField;
        
        private System.Nullable<int> RealFlagField;
        
        private System.Nullable<System.DateTime> SubTimeField;
        
        private string TagField;
        
        private int UseFlagField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AccuInstrFlag
        {
            get
            {
                return this.AccuInstrFlagField;
            }
            set
            {
                this.AccuInstrFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BegShiftTime
        {
            get
            {
                return this.BegShiftTimeField;
            }
            set
            {
                this.BegShiftTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Coefficient
        {
            get
            {
                return this.CoefficientField;
            }
            set
            {
                this.CoefficientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DimensionId
        {
            get
            {
                return this.DimensionIdField;
            }
            set
            {
                this.DimensionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndShiftTime
        {
            get
            {
                return this.EndShiftTimeField;
            }
            set
            {
                this.EndShiftTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HasChild
        {
            get
            {
                return this.HasChildField;
            }
            set
            {
                this.HasChildField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long InitId
        {
            get
            {
                return this.InitIdField;
            }
            set
            {
                this.InitIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> InitPreVal
        {
            get
            {
                return this.InitPreValField;
            }
            set
            {
                this.InitPreValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> InitTime
        {
            get
            {
                return this.InitTimeField;
            }
            set
            {
                this.InitTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> InitVal
        {
            get
            {
                return this.InitValField;
            }
            set
            {
                this.InitValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstrAlias
        {
            get
            {
                return this.InstrAliasField;
            }
            set
            {
                this.InstrAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long InstrDataId
        {
            get
            {
                return this.InstrDataIdField;
            }
            set
            {
                this.InstrDataIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long InstrId
        {
            get
            {
                return this.InstrIdField;
            }
            set
            {
                this.InstrIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> InstrRawVal
        {
            get
            {
                return this.InstrRawValField;
            }
            set
            {
                this.InstrRawValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> InstrTagStat
        {
            get
            {
                return this.InstrTagStatField;
            }
            set
            {
                this.InstrTagStatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> InstrVadVal
        {
            get
            {
                return this.InstrVadValField;
            }
            set
            {
                this.InstrVadValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PCITC.MES.MM.CU.BLL.Entity.InstrumentMeasureRec1[] ListSub1
        {
            get
            {
                return this.ListSub1Field;
            }
            set
            {
                this.ListSub1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MtrlAlias
        {
            get
            {
                return this.MtrlAliasField;
            }
            set
            {
                this.MtrlAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> MtrlId
        {
            get
            {
                return this.MtrlIdField;
            }
            set
            {
                this.MtrlIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> NetWeight
        {
            get
            {
                return this.NetWeightField;
            }
            set
            {
                this.NetWeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NodeAlias
        {
            get
            {
                return this.NodeAliasField;
            }
            set
            {
                this.NodeAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NodeAreaId
        {
            get
            {
                return this.NodeAreaIdField;
            }
            set
            {
                this.NodeAreaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> NodeId
        {
            get
            {
                return this.NodeIdField;
            }
            set
            {
                this.NodeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Oprter
        {
            get
            {
                return this.OprterField;
            }
            set
            {
                this.OprterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PNodeAreaId
        {
            get
            {
                return this.PNodeAreaIdField;
            }
            set
            {
                this.PNodeAreaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PreVadVal
        {
            get
            {
                return this.PreVadValField;
            }
            set
            {
                this.PreVadValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> QutyRankId
        {
            get
            {
                return this.QutyRankIdField;
            }
            set
            {
                this.QutyRankIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RankName
        {
            get
            {
                return this.RankNameField;
            }
            set
            {
                this.RankNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReadTime
        {
            get
            {
                return this.ReadTimeField;
            }
            set
            {
                this.ReadTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RealFlag
        {
            get
            {
                return this.RealFlagField;
            }
            set
            {
                this.RealFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SubTime
        {
            get
            {
                return this.SubTimeField;
            }
            set
            {
                this.SubTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tag
        {
            get
            {
                return this.TagField;
            }
            set
            {
                this.TagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UseFlag
        {
            get
            {
                return this.UseFlagField;
            }
            set
            {
                this.UseFlagField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonProp", Namespace="http://schemas.datacontract.org/2004/07/PCITC.MES.MM.CU.BLL.Entity")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCITC.MES.MM.CU.BLL.Entity.InstrumentMeasureRec1))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCITC.MES.MM.CU.BLL.Entity.UnitStateRec))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCITC.MES.MM.CU.BLL.Entity.CommonHierListOfUnitTankMaterielRecuRt2sX8z))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCITC.MES.MM.CU.BLL.Entity.UnitTankMeasureRec))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCITC.MES.MM.CU.BLL.Entity.CommonHierListOfUnitInOutSubuRt2sX8z))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCITC.MES.MM.CU.BLL.Entity.UnitInOutRec))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCITC.MES.MM.CU.BLL.Entity.InstrumentMeasureRec))]
    public partial class CommonProp : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<System.DateTime> CmtTimeField;
        
        private string RecFlagField;
        
        private System.Nullable<System.DateTime> ShiftBeginTimeField;
        
        private System.Nullable<System.DateTime> ShiftEndTimeField;
        
        private string UserIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CmtTime
        {
            get
            {
                return this.CmtTimeField;
            }
            set
            {
                this.CmtTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecFlag
        {
            get
            {
                return this.RecFlagField;
            }
            set
            {
                this.RecFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ShiftBeginTime
        {
            get
            {
                return this.ShiftBeginTimeField;
            }
            set
            {
                this.ShiftBeginTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ShiftEndTime
        {
            get
            {
                return this.ShiftEndTimeField;
            }
            set
            {
                this.ShiftEndTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InstrumentMeasureRec1", Namespace="http://schemas.datacontract.org/2004/07/PCITC.MES.MM.CU.BLL.Entity")]
    public partial class InstrumentMeasureRec1 : PCITC.MES.MM.CU.BLL.Entity.CommonProp
    {
        
        private System.Nullable<int> AccuInstrFlagField;
        
        private System.Nullable<System.DateTime> BegShiftTimeField;
        
        private System.Nullable<decimal> CoefficientField;
        
        private int DimensionIdField;
        
        private System.Nullable<System.DateTime> EndShiftTimeField;
        
        private string HasChildField;
        
        private long IdField;
        
        private long InitIdField;
        
        private System.Nullable<decimal> InitPreValField;
        
        private System.Nullable<System.DateTime> InitTimeField;
        
        private System.Nullable<decimal> InitValField;
        
        private string InstrAliasField;
        
        private long InstrDataIdField;
        
        private long InstrIdField;
        
        private System.Nullable<decimal> InstrRawValField;
        
        private System.Nullable<int> InstrTagStatField;
        
        private System.Nullable<decimal> InstrVadValField;
        
        private string MtrlAliasField;
        
        private System.Nullable<long> MtrlIdField;
        
        private System.Nullable<decimal> NetWeightField;
        
        private string NodeAliasField;
        
        private long NodeAreaIdField;
        
        private System.Nullable<long> NodeIdField;
        
        private string OprterField;
        
        private long PNodeAreaIdField;
        
        private System.Nullable<decimal> PreVadValField;
        
        private System.Nullable<long> QutyRankIdField;
        
        private string RankNameField;
        
        private System.Nullable<System.DateTime> ReadTimeField;
        
        private System.Nullable<int> RealFlagField;
        
        private System.Nullable<System.DateTime> SubTimeField;
        
        private string TagField;
        
        private int UseFlagField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AccuInstrFlag
        {
            get
            {
                return this.AccuInstrFlagField;
            }
            set
            {
                this.AccuInstrFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BegShiftTime
        {
            get
            {
                return this.BegShiftTimeField;
            }
            set
            {
                this.BegShiftTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Coefficient
        {
            get
            {
                return this.CoefficientField;
            }
            set
            {
                this.CoefficientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DimensionId
        {
            get
            {
                return this.DimensionIdField;
            }
            set
            {
                this.DimensionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndShiftTime
        {
            get
            {
                return this.EndShiftTimeField;
            }
            set
            {
                this.EndShiftTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HasChild
        {
            get
            {
                return this.HasChildField;
            }
            set
            {
                this.HasChildField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long InitId
        {
            get
            {
                return this.InitIdField;
            }
            set
            {
                this.InitIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> InitPreVal
        {
            get
            {
                return this.InitPreValField;
            }
            set
            {
                this.InitPreValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> InitTime
        {
            get
            {
                return this.InitTimeField;
            }
            set
            {
                this.InitTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> InitVal
        {
            get
            {
                return this.InitValField;
            }
            set
            {
                this.InitValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstrAlias
        {
            get
            {
                return this.InstrAliasField;
            }
            set
            {
                this.InstrAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long InstrDataId
        {
            get
            {
                return this.InstrDataIdField;
            }
            set
            {
                this.InstrDataIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long InstrId
        {
            get
            {
                return this.InstrIdField;
            }
            set
            {
                this.InstrIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> InstrRawVal
        {
            get
            {
                return this.InstrRawValField;
            }
            set
            {
                this.InstrRawValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> InstrTagStat
        {
            get
            {
                return this.InstrTagStatField;
            }
            set
            {
                this.InstrTagStatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> InstrVadVal
        {
            get
            {
                return this.InstrVadValField;
            }
            set
            {
                this.InstrVadValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MtrlAlias
        {
            get
            {
                return this.MtrlAliasField;
            }
            set
            {
                this.MtrlAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> MtrlId
        {
            get
            {
                return this.MtrlIdField;
            }
            set
            {
                this.MtrlIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> NetWeight
        {
            get
            {
                return this.NetWeightField;
            }
            set
            {
                this.NetWeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NodeAlias
        {
            get
            {
                return this.NodeAliasField;
            }
            set
            {
                this.NodeAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NodeAreaId
        {
            get
            {
                return this.NodeAreaIdField;
            }
            set
            {
                this.NodeAreaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> NodeId
        {
            get
            {
                return this.NodeIdField;
            }
            set
            {
                this.NodeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Oprter
        {
            get
            {
                return this.OprterField;
            }
            set
            {
                this.OprterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PNodeAreaId
        {
            get
            {
                return this.PNodeAreaIdField;
            }
            set
            {
                this.PNodeAreaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PreVadVal
        {
            get
            {
                return this.PreVadValField;
            }
            set
            {
                this.PreVadValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> QutyRankId
        {
            get
            {
                return this.QutyRankIdField;
            }
            set
            {
                this.QutyRankIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RankName
        {
            get
            {
                return this.RankNameField;
            }
            set
            {
                this.RankNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReadTime
        {
            get
            {
                return this.ReadTimeField;
            }
            set
            {
                this.ReadTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RealFlag
        {
            get
            {
                return this.RealFlagField;
            }
            set
            {
                this.RealFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SubTime
        {
            get
            {
                return this.SubTimeField;
            }
            set
            {
                this.SubTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tag
        {
            get
            {
                return this.TagField;
            }
            set
            {
                this.TagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UseFlag
        {
            get
            {
                return this.UseFlagField;
            }
            set
            {
                this.UseFlagField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnitStateRec", Namespace="http://schemas.datacontract.org/2004/07/PCITC.MES.MM.CU.BLL.Entity")]
    public partial class UnitStateRec : PCITC.MES.MM.CU.BLL.Entity.CommonProp
    {
        
        private System.Nullable<System.DateTime> BegShiftTimeField;
        
        private int BillSealFlgField;
        
        private System.Nullable<System.DateTime> BillSealTimeField;
        
        private string DesField;
        
        private System.Nullable<System.DateTime> EndShiftTimeField;
        
        private System.Nullable<long> UnitIdField;
        
        private long UnitStateIdField;
        
        private long UnitStateRecIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BegShiftTime
        {
            get
            {
                return this.BegShiftTimeField;
            }
            set
            {
                this.BegShiftTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BillSealFlg
        {
            get
            {
                return this.BillSealFlgField;
            }
            set
            {
                this.BillSealFlgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BillSealTime
        {
            get
            {
                return this.BillSealTimeField;
            }
            set
            {
                this.BillSealTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Des
        {
            get
            {
                return this.DesField;
            }
            set
            {
                this.DesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndShiftTime
        {
            get
            {
                return this.EndShiftTimeField;
            }
            set
            {
                this.EndShiftTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> UnitId
        {
            get
            {
                return this.UnitIdField;
            }
            set
            {
                this.UnitIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UnitStateId
        {
            get
            {
                return this.UnitStateIdField;
            }
            set
            {
                this.UnitStateIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UnitStateRecId
        {
            get
            {
                return this.UnitStateRecIdField;
            }
            set
            {
                this.UnitStateRecIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonHierListOfUnitTankMaterielRecuRt2sX8z", Namespace="http://schemas.datacontract.org/2004/07/PCITC.MES.MM.CU.BLL.Entity")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCITC.MES.MM.CU.BLL.Entity.UnitTankMeasureRec))]
    public partial class CommonHierListOfUnitTankMaterielRecuRt2sX8z : PCITC.MES.MM.CU.BLL.Entity.CommonProp
    {
        
        private PCITC.MES.MM.CU.BLL.Entity.UnitTankMaterielRec[] listSubField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PCITC.MES.MM.CU.BLL.Entity.UnitTankMaterielRec[] listSub
        {
            get
            {
                return this.listSubField;
            }
            set
            {
                this.listSubField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnitTankMeasureRec", Namespace="http://schemas.datacontract.org/2004/07/PCITC.MES.MM.CU.BLL.Entity")]
    public partial class UnitTankMeasureRec : PCITC.MES.MM.CU.BLL.Entity.CommonHierListOfUnitTankMaterielRecuRt2sX8z
    {
        
        private decimal AcidFctrField;
        
        private decimal AdjValField;
        
        private decimal AlklFctrField;
        
        private System.DateTime BegShiftTimeField;
        
        private System.DateTime ChkTimeField;
        
        private long ChkTypeField;
        
        private string ChkUserIdField;
        
        private string CmtUserIdField;
        
        private decimal CntrtnPrcntField;
        
        private string CrtDateField;
        
        private string CrtUserIdField;
        
        private string CrtUserNameField;
        
        private System.DateTime EndShiftTimeField;
        
        private decimal FixprsrAdjValField;
        
        private string HasChildField;
        
        private decimal InstChkValField;
        
        private decimal MaxSafeVolField;
        
        private string MemoField;
        
        private string MntDateField;
        
        private string MntUserIdField;
        
        private string MntUserNameField;
        
        private decimal MnulChkValField;
        
        private long MtrlIdField;
        
        private decimal NetWeightField;
        
        private decimal NetoilMassField;
        
        private decimal NetoilVolField;
        
        private long NodeIdField;
        
        private decimal OffsetValField;
        
        private decimal OilDnstField;
        
        private decimal OilTempField;
        
        private decimal PreWeightField;
        
        private decimal PresField;
        
        private string RankNameField;
        
        private string SdlnNodeAliasField;
        
        private long StkhsMeasRecIdField;
        
        private int SubmitStateField;
        
        private long TankChkIdField;
        
        private decimal TankConValField;
        
        private string TankNodeAliasField;
        
        private long TankNodeIdField;
        
        private string TankNodeNameField;
        
        private int TankQutyRankIdField;
        
        private int TankTypeIdField;
        
        private decimal TempAdjValField;
        
        private decimal VcfValField;
        
        private int VersionField;
        
        private decimal WaterRateField;
        
        private decimal WaterVolField;
        
        private decimal WatrHghtField;
        
        private decimal WeightField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AcidFctr
        {
            get
            {
                return this.AcidFctrField;
            }
            set
            {
                this.AcidFctrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AdjVal
        {
            get
            {
                return this.AdjValField;
            }
            set
            {
                this.AdjValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AlklFctr
        {
            get
            {
                return this.AlklFctrField;
            }
            set
            {
                this.AlklFctrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BegShiftTime
        {
            get
            {
                return this.BegShiftTimeField;
            }
            set
            {
                this.BegShiftTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ChkTime
        {
            get
            {
                return this.ChkTimeField;
            }
            set
            {
                this.ChkTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ChkType
        {
            get
            {
                return this.ChkTypeField;
            }
            set
            {
                this.ChkTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChkUserId
        {
            get
            {
                return this.ChkUserIdField;
            }
            set
            {
                this.ChkUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CmtUserId
        {
            get
            {
                return this.CmtUserIdField;
            }
            set
            {
                this.CmtUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CntrtnPrcnt
        {
            get
            {
                return this.CntrtnPrcntField;
            }
            set
            {
                this.CntrtnPrcntField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrtDate
        {
            get
            {
                return this.CrtDateField;
            }
            set
            {
                this.CrtDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrtUserId
        {
            get
            {
                return this.CrtUserIdField;
            }
            set
            {
                this.CrtUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrtUserName
        {
            get
            {
                return this.CrtUserNameField;
            }
            set
            {
                this.CrtUserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndShiftTime
        {
            get
            {
                return this.EndShiftTimeField;
            }
            set
            {
                this.EndShiftTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FixprsrAdjVal
        {
            get
            {
                return this.FixprsrAdjValField;
            }
            set
            {
                this.FixprsrAdjValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HasChild
        {
            get
            {
                return this.HasChildField;
            }
            set
            {
                this.HasChildField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InstChkVal
        {
            get
            {
                return this.InstChkValField;
            }
            set
            {
                this.InstChkValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MaxSafeVol
        {
            get
            {
                return this.MaxSafeVolField;
            }
            set
            {
                this.MaxSafeVolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Memo
        {
            get
            {
                return this.MemoField;
            }
            set
            {
                this.MemoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MntDate
        {
            get
            {
                return this.MntDateField;
            }
            set
            {
                this.MntDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MntUserId
        {
            get
            {
                return this.MntUserIdField;
            }
            set
            {
                this.MntUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MntUserName
        {
            get
            {
                return this.MntUserNameField;
            }
            set
            {
                this.MntUserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MnulChkVal
        {
            get
            {
                return this.MnulChkValField;
            }
            set
            {
                this.MnulChkValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MtrlId
        {
            get
            {
                return this.MtrlIdField;
            }
            set
            {
                this.MtrlIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NetWeight
        {
            get
            {
                return this.NetWeightField;
            }
            set
            {
                this.NetWeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NetoilMass
        {
            get
            {
                return this.NetoilMassField;
            }
            set
            {
                this.NetoilMassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NetoilVol
        {
            get
            {
                return this.NetoilVolField;
            }
            set
            {
                this.NetoilVolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NodeId
        {
            get
            {
                return this.NodeIdField;
            }
            set
            {
                this.NodeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OffsetVal
        {
            get
            {
                return this.OffsetValField;
            }
            set
            {
                this.OffsetValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OilDnst
        {
            get
            {
                return this.OilDnstField;
            }
            set
            {
                this.OilDnstField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OilTemp
        {
            get
            {
                return this.OilTempField;
            }
            set
            {
                this.OilTempField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PreWeight
        {
            get
            {
                return this.PreWeightField;
            }
            set
            {
                this.PreWeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Pres
        {
            get
            {
                return this.PresField;
            }
            set
            {
                this.PresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RankName
        {
            get
            {
                return this.RankNameField;
            }
            set
            {
                this.RankNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SdlnNodeAlias
        {
            get
            {
                return this.SdlnNodeAliasField;
            }
            set
            {
                this.SdlnNodeAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long StkhsMeasRecId
        {
            get
            {
                return this.StkhsMeasRecIdField;
            }
            set
            {
                this.StkhsMeasRecIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubmitState
        {
            get
            {
                return this.SubmitStateField;
            }
            set
            {
                this.SubmitStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TankChkId
        {
            get
            {
                return this.TankChkIdField;
            }
            set
            {
                this.TankChkIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TankConVal
        {
            get
            {
                return this.TankConValField;
            }
            set
            {
                this.TankConValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TankNodeAlias
        {
            get
            {
                return this.TankNodeAliasField;
            }
            set
            {
                this.TankNodeAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TankNodeId
        {
            get
            {
                return this.TankNodeIdField;
            }
            set
            {
                this.TankNodeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TankNodeName
        {
            get
            {
                return this.TankNodeNameField;
            }
            set
            {
                this.TankNodeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TankQutyRankId
        {
            get
            {
                return this.TankQutyRankIdField;
            }
            set
            {
                this.TankQutyRankIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TankTypeId
        {
            get
            {
                return this.TankTypeIdField;
            }
            set
            {
                this.TankTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TempAdjVal
        {
            get
            {
                return this.TempAdjValField;
            }
            set
            {
                this.TempAdjValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal VcfVal
        {
            get
            {
                return this.VcfValField;
            }
            set
            {
                this.VcfValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal WaterRate
        {
            get
            {
                return this.WaterRateField;
            }
            set
            {
                this.WaterRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal WaterVol
        {
            get
            {
                return this.WaterVolField;
            }
            set
            {
                this.WaterVolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal WatrHght
        {
            get
            {
                return this.WatrHghtField;
            }
            set
            {
                this.WatrHghtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Weight
        {
            get
            {
                return this.WeightField;
            }
            set
            {
                this.WeightField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonHierListOfUnitInOutSubuRt2sX8z", Namespace="http://schemas.datacontract.org/2004/07/PCITC.MES.MM.CU.BLL.Entity")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PCITC.MES.MM.CU.BLL.Entity.UnitInOutRec))]
    public partial class CommonHierListOfUnitInOutSubuRt2sX8z : PCITC.MES.MM.CU.BLL.Entity.CommonProp
    {
        
        private PCITC.MES.MM.CU.BLL.Entity.UnitInOutSub[] listSubField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PCITC.MES.MM.CU.BLL.Entity.UnitInOutSub[] listSub
        {
            get
            {
                return this.listSubField;
            }
            set
            {
                this.listSubField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnitInOutRec", Namespace="http://schemas.datacontract.org/2004/07/PCITC.MES.MM.CU.BLL.Entity")]
    public partial class UnitInOutRec : PCITC.MES.MM.CU.BLL.Entity.CommonHierListOfUnitInOutSubuRt2sX8z
    {
        
        private System.Nullable<decimal> AftCtchValField;
        
        private System.Nullable<decimal> AreaConValField;
        
        private string AreaFormField;
        
        private System.Nullable<decimal> AreaRowValField;
        
        private long DisplayOrderField;
        
        private System.Nullable<decimal> EvaluDiffValField;
        
        private string FormulaField;
        
        private string HasChildField;
        
        private string InOutTypeNameField;
        
        private string MtrlAliasField;
        
        private long MtrlIdField;
        
        private string NodeAliasField;
        
        private long NodeIdField;
        
        private System.Nullable<decimal> PreCtchValField;
        
        private long RankIdField;
        
        private string RankNameField;
        
        private long RecIdField;
        
        private System.Nullable<System.DateTime> SavTimeField;
        
        private string SavUserIdField;
        
        private System.Nullable<decimal> SaveCtchConValField;
        
        private System.Nullable<decimal> SaveCtchValField;
        
        private System.Nullable<decimal> SdlnAfValField;
        
        private System.Nullable<decimal> SdlnOriValField;
        
        private string ShiftBtchField;
        
        private System.Nullable<System.DateTime> UnitVadTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> AftCtchVal
        {
            get
            {
                return this.AftCtchValField;
            }
            set
            {
                this.AftCtchValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> AreaConVal
        {
            get
            {
                return this.AreaConValField;
            }
            set
            {
                this.AreaConValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaForm
        {
            get
            {
                return this.AreaFormField;
            }
            set
            {
                this.AreaFormField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> AreaRowVal
        {
            get
            {
                return this.AreaRowValField;
            }
            set
            {
                this.AreaRowValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DisplayOrder
        {
            get
            {
                return this.DisplayOrderField;
            }
            set
            {
                this.DisplayOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> EvaluDiffVal
        {
            get
            {
                return this.EvaluDiffValField;
            }
            set
            {
                this.EvaluDiffValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Formula
        {
            get
            {
                return this.FormulaField;
            }
            set
            {
                this.FormulaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HasChild
        {
            get
            {
                return this.HasChildField;
            }
            set
            {
                this.HasChildField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InOutTypeName
        {
            get
            {
                return this.InOutTypeNameField;
            }
            set
            {
                this.InOutTypeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MtrlAlias
        {
            get
            {
                return this.MtrlAliasField;
            }
            set
            {
                this.MtrlAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MtrlId
        {
            get
            {
                return this.MtrlIdField;
            }
            set
            {
                this.MtrlIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NodeAlias
        {
            get
            {
                return this.NodeAliasField;
            }
            set
            {
                this.NodeAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NodeId
        {
            get
            {
                return this.NodeIdField;
            }
            set
            {
                this.NodeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PreCtchVal
        {
            get
            {
                return this.PreCtchValField;
            }
            set
            {
                this.PreCtchValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RankId
        {
            get
            {
                return this.RankIdField;
            }
            set
            {
                this.RankIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RankName
        {
            get
            {
                return this.RankNameField;
            }
            set
            {
                this.RankNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId
        {
            get
            {
                return this.RecIdField;
            }
            set
            {
                this.RecIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SavTime
        {
            get
            {
                return this.SavTimeField;
            }
            set
            {
                this.SavTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SavUserId
        {
            get
            {
                return this.SavUserIdField;
            }
            set
            {
                this.SavUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SaveCtchConVal
        {
            get
            {
                return this.SaveCtchConValField;
            }
            set
            {
                this.SaveCtchConValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SaveCtchVal
        {
            get
            {
                return this.SaveCtchValField;
            }
            set
            {
                this.SaveCtchValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SdlnAfVal
        {
            get
            {
                return this.SdlnAfValField;
            }
            set
            {
                this.SdlnAfValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SdlnOriVal
        {
            get
            {
                return this.SdlnOriValField;
            }
            set
            {
                this.SdlnOriValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShiftBtch
        {
            get
            {
                return this.ShiftBtchField;
            }
            set
            {
                this.ShiftBtchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UnitVadTime
        {
            get
            {
                return this.UnitVadTimeField;
            }
            set
            {
                this.UnitVadTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnitTankMaterielRec", Namespace="http://schemas.datacontract.org/2004/07/PCITC.MES.MM.CU.BLL.Entity")]
    public partial class UnitTankMaterielRec : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MtrlAliasField;
        
        private System.Nullable<long> MtrlIdField;
        
        private string MtrlNameField;
        
        private System.Nullable<decimal> MtrlPrcntField;
        
        private System.Nullable<long> MtrlRecIdField;
        
        private System.Nullable<long> QutyRankIdField;
        
        private string RankNameField;
        
        private string RecFlagField;
        
        private System.Nullable<long> StkhsMeasRecIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MtrlAlias
        {
            get
            {
                return this.MtrlAliasField;
            }
            set
            {
                this.MtrlAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> MtrlId
        {
            get
            {
                return this.MtrlIdField;
            }
            set
            {
                this.MtrlIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MtrlName
        {
            get
            {
                return this.MtrlNameField;
            }
            set
            {
                this.MtrlNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> MtrlPrcnt
        {
            get
            {
                return this.MtrlPrcntField;
            }
            set
            {
                this.MtrlPrcntField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> MtrlRecId
        {
            get
            {
                return this.MtrlRecIdField;
            }
            set
            {
                this.MtrlRecIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> QutyRankId
        {
            get
            {
                return this.QutyRankIdField;
            }
            set
            {
                this.QutyRankIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RankName
        {
            get
            {
                return this.RankNameField;
            }
            set
            {
                this.RankNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecFlag
        {
            get
            {
                return this.RecFlagField;
            }
            set
            {
                this.RecFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> StkhsMeasRecId
        {
            get
            {
                return this.StkhsMeasRecIdField;
            }
            set
            {
                this.StkhsMeasRecIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnitInOutSub", Namespace="http://schemas.datacontract.org/2004/07/PCITC.MES.MM.CU.BLL.Entity")]
    public partial class UnitInOutSub : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<decimal> AdjValField;
        
        private decimal AftAdjValField;
        
        private decimal AftConValField;
        
        private string InstrAliasField;
        
        private long InstrIdField;
        
        private string MeasureTypeField;
        
        private long MtrlIdField;
        
        private long NodeIdField;
        
        private string NodeTypeField;
        
        private decimal PreAdjValField;
        
        private System.Nullable<decimal> PreWeightField;
        
        private long RankIdField;
        
        private long StkhsMeasRecIdField;
        
        private string TagField;
        
        private System.Nullable<decimal> WeightField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> AdjVal
        {
            get
            {
                return this.AdjValField;
            }
            set
            {
                this.AdjValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AftAdjVal
        {
            get
            {
                return this.AftAdjValField;
            }
            set
            {
                this.AftAdjValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AftConVal
        {
            get
            {
                return this.AftConValField;
            }
            set
            {
                this.AftConValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstrAlias
        {
            get
            {
                return this.InstrAliasField;
            }
            set
            {
                this.InstrAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long InstrId
        {
            get
            {
                return this.InstrIdField;
            }
            set
            {
                this.InstrIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeasureType
        {
            get
            {
                return this.MeasureTypeField;
            }
            set
            {
                this.MeasureTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MtrlId
        {
            get
            {
                return this.MtrlIdField;
            }
            set
            {
                this.MtrlIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NodeId
        {
            get
            {
                return this.NodeIdField;
            }
            set
            {
                this.NodeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NodeType
        {
            get
            {
                return this.NodeTypeField;
            }
            set
            {
                this.NodeTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PreAdjVal
        {
            get
            {
                return this.PreAdjValField;
            }
            set
            {
                this.PreAdjValField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PreWeight
        {
            get
            {
                return this.PreWeightField;
            }
            set
            {
                this.PreWeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RankId
        {
            get
            {
                return this.RankIdField;
            }
            set
            {
                this.RankIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long StkhsMeasRecId
        {
            get
            {
                return this.StkhsMeasRecIdField;
            }
            set
            {
                this.StkhsMeasRecIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tag
        {
            get
            {
                return this.TagField;
            }
            set
            {
                this.TagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Weight
        {
            get
            {
                return this.WeightField;
            }
            set
            {
                this.WeightField = value;
            }
        }
    }
}
namespace PCITC.MES.MM.CU.BLL.Entity.Interope
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CuIopRetVal", Namespace="http://schemas.datacontract.org/2004/07/PCITC.MES.MM.CU.BLL.Entity.Interope")]
    public partial class CuIopRetVal : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrmsgField;
        
        private string ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Errmsg
        {
            get
            {
                return this.ErrmsgField;
            }
            set
            {
                this.ErrmsgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICuOperateSrv")]
public interface ICuOperateSrv
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuOperateSrv/GetMeasureRecs", ReplyAction="http://tempuri.org/ICuOperateSrv/GetMeasureRecsResponse")]
    PCITC.MES.MM.CU.BLL.Entity.InstrumentMeasureRec[] GetMeasureRecs(PCITC.MES.MM.CU.BLL.Entity.UnitShiftTime ust);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuOperateSrv/GetMeasureRecs", ReplyAction="http://tempuri.org/ICuOperateSrv/GetMeasureRecsResponse")]
    System.Threading.Tasks.Task<PCITC.MES.MM.CU.BLL.Entity.InstrumentMeasureRec[]> GetMeasureRecsAsync(PCITC.MES.MM.CU.BLL.Entity.UnitShiftTime ust);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuOperateSrv/SaveInstrumentMeasure", ReplyAction="http://tempuri.org/ICuOperateSrv/SaveInstrumentMeasureResponse")]
    PCITC.MES.MM.CU.BLL.Entity.Interope.CuIopRetVal SaveInstrumentMeasure(PCITC.MES.MM.CU.BLL.Entity.InstrumentMeasureRec[] recList, PCITC.MES.MM.CU.BLL.Entity.UnitStateRec unitStateRec, System.DateTime shiftBeginTime, System.DateTime shiftEndTime, long unitId, string userId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuOperateSrv/SaveInstrumentMeasure", ReplyAction="http://tempuri.org/ICuOperateSrv/SaveInstrumentMeasureResponse")]
    System.Threading.Tasks.Task<PCITC.MES.MM.CU.BLL.Entity.Interope.CuIopRetVal> SaveInstrumentMeasureAsync(PCITC.MES.MM.CU.BLL.Entity.InstrumentMeasureRec[] recList, PCITC.MES.MM.CU.BLL.Entity.UnitStateRec unitStateRec, System.DateTime shiftBeginTime, System.DateTime shiftEndTime, long unitId, string userId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuOperateSrv/QueryAndSaveInstrMeasure", ReplyAction="http://tempuri.org/ICuOperateSrv/QueryAndSaveInstrMeasureResponse")]
    bool QueryAndSaveInstrMeasure(long unitId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuOperateSrv/QueryAndSaveInstrMeasure", ReplyAction="http://tempuri.org/ICuOperateSrv/QueryAndSaveInstrMeasureResponse")]
    System.Threading.Tasks.Task<bool> QueryAndSaveInstrMeasureAsync(long unitId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuOperateSrv/GetTankMeasureRecs", ReplyAction="http://tempuri.org/ICuOperateSrv/GetTankMeasureRecsResponse")]
    PCITC.MES.MM.CU.BLL.Entity.UnitTankMeasureRec[] GetTankMeasureRecs(PCITC.MES.MM.CU.BLL.Entity.UnitShiftTime ust);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuOperateSrv/GetTankMeasureRecs", ReplyAction="http://tempuri.org/ICuOperateSrv/GetTankMeasureRecsResponse")]
    System.Threading.Tasks.Task<PCITC.MES.MM.CU.BLL.Entity.UnitTankMeasureRec[]> GetTankMeasureRecsAsync(PCITC.MES.MM.CU.BLL.Entity.UnitShiftTime ust);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuOperateSrv/SaveUnitTankMeasureRec", ReplyAction="http://tempuri.org/ICuOperateSrv/SaveUnitTankMeasureRecResponse")]
    PCITC.MES.MM.CU.BLL.Entity.Interope.CuIopRetVal SaveUnitTankMeasureRec(PCITC.MES.MM.CU.BLL.Entity.UnitTankMeasureRec[] lstUtmr, PCITC.MES.MM.CU.BLL.Entity.UnitStateRec unitStateRec, System.DateTime shiftBeginTime, System.DateTime shiftEndTime, long unitId, string userId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuOperateSrv/SaveUnitTankMeasureRec", ReplyAction="http://tempuri.org/ICuOperateSrv/SaveUnitTankMeasureRecResponse")]
    System.Threading.Tasks.Task<PCITC.MES.MM.CU.BLL.Entity.Interope.CuIopRetVal> SaveUnitTankMeasureRecAsync(PCITC.MES.MM.CU.BLL.Entity.UnitTankMeasureRec[] lstUtmr, PCITC.MES.MM.CU.BLL.Entity.UnitStateRec unitStateRec, System.DateTime shiftBeginTime, System.DateTime shiftEndTime, long unitId, string userId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuOperateSrv/QueryAndSaveUnitTankRec", ReplyAction="http://tempuri.org/ICuOperateSrv/QueryAndSaveUnitTankRecResponse")]
    bool QueryAndSaveUnitTankRec(long unitId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuOperateSrv/QueryAndSaveUnitTankRec", ReplyAction="http://tempuri.org/ICuOperateSrv/QueryAndSaveUnitTankRecResponse")]
    System.Threading.Tasks.Task<bool> QueryAndSaveUnitTankRecAsync(long unitId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuOperateSrv/ReCulcInOutRecs", ReplyAction="http://tempuri.org/ICuOperateSrv/ReCulcInOutRecsResponse")]
    PCITC.MES.MM.CU.BLL.Entity.UnitInOutRec[] ReCulcInOutRecs(PCITC.MES.MM.CU.BLL.Entity.UnitShiftTime ust);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuOperateSrv/ReCulcInOutRecs", ReplyAction="http://tempuri.org/ICuOperateSrv/ReCulcInOutRecsResponse")]
    System.Threading.Tasks.Task<PCITC.MES.MM.CU.BLL.Entity.UnitInOutRec[]> ReCulcInOutRecsAsync(PCITC.MES.MM.CU.BLL.Entity.UnitShiftTime ust);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuOperateSrv/SaveInOutRec", ReplyAction="http://tempuri.org/ICuOperateSrv/SaveInOutRecResponse")]
    PCITC.MES.MM.CU.BLL.Entity.Interope.CuIopRetVal SaveInOutRec(PCITC.MES.MM.CU.BLL.Entity.UnitInOutRec[] listUior, System.DateTime shiftBeginTime, System.DateTime shiftEndTime, long unitId, string userId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuOperateSrv/SaveInOutRec", ReplyAction="http://tempuri.org/ICuOperateSrv/SaveInOutRecResponse")]
    System.Threading.Tasks.Task<PCITC.MES.MM.CU.BLL.Entity.Interope.CuIopRetVal> SaveInOutRecAsync(PCITC.MES.MM.CU.BLL.Entity.UnitInOutRec[] listUior, System.DateTime shiftBeginTime, System.DateTime shiftEndTime, long unitId, string userId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuOperateSrv/RecAndSaveInOutPutRec", ReplyAction="http://tempuri.org/ICuOperateSrv/RecAndSaveInOutPutRecResponse")]
    bool RecAndSaveInOutPutRec(long unitId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuOperateSrv/RecAndSaveInOutPutRec", ReplyAction="http://tempuri.org/ICuOperateSrv/RecAndSaveInOutPutRecResponse")]
    System.Threading.Tasks.Task<bool> RecAndSaveInOutPutRecAsync(long unitId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuOperateSrv/UnitSeal", ReplyAction="http://tempuri.org/ICuOperateSrv/UnitSealResponse")]
    bool UnitSeal(long unitId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuOperateSrv/UnitSeal", ReplyAction="http://tempuri.org/ICuOperateSrv/UnitSealResponse")]
    System.Threading.Tasks.Task<bool> UnitSealAsync(long unitId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuOperateSrv/UnitUnSeal", ReplyAction="http://tempuri.org/ICuOperateSrv/UnitUnSealResponse")]
    bool UnitUnSeal(long unitId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuOperateSrv/UnitUnSeal", ReplyAction="http://tempuri.org/ICuOperateSrv/UnitUnSealResponse")]
    System.Threading.Tasks.Task<bool> UnitUnSealAsync(long unitId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuOperateSrv/ShiftDataAutoCalcAndSeal", ReplyAction="http://tempuri.org/ICuOperateSrv/ShiftDataAutoCalcAndSealResponse")]
    bool ShiftDataAutoCalcAndSeal(long unitId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuOperateSrv/ShiftDataAutoCalcAndSeal", ReplyAction="http://tempuri.org/ICuOperateSrv/ShiftDataAutoCalcAndSealResponse")]
    System.Threading.Tasks.Task<bool> ShiftDataAutoCalcAndSealAsync(long unitId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuOperateSrv/QueryAndSaveMeaNodeInstrMeaSureMent", ReplyAction="http://tempuri.org/ICuOperateSrv/QueryAndSaveMeaNodeInstrMeaSureMentResponse")]
    bool QueryAndSaveMeaNodeInstrMeaSureMent(long nodeAreaId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuOperateSrv/QueryAndSaveMeaNodeInstrMeaSureMent", ReplyAction="http://tempuri.org/ICuOperateSrv/QueryAndSaveMeaNodeInstrMeaSureMentResponse")]
    System.Threading.Tasks.Task<bool> QueryAndSaveMeaNodeInstrMeaSureMentAsync(long nodeAreaId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICuOperateSrvChannel : ICuOperateSrv, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CuOperateSrvClient : System.ServiceModel.ClientBase<ICuOperateSrv>, ICuOperateSrv
{
    
    public CuOperateSrvClient()
    {
    }
    
    public CuOperateSrvClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CuOperateSrvClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CuOperateSrvClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CuOperateSrvClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public PCITC.MES.MM.CU.BLL.Entity.InstrumentMeasureRec[] GetMeasureRecs(PCITC.MES.MM.CU.BLL.Entity.UnitShiftTime ust)
    {
        return base.Channel.GetMeasureRecs(ust);
    }
    
    public System.Threading.Tasks.Task<PCITC.MES.MM.CU.BLL.Entity.InstrumentMeasureRec[]> GetMeasureRecsAsync(PCITC.MES.MM.CU.BLL.Entity.UnitShiftTime ust)
    {
        return base.Channel.GetMeasureRecsAsync(ust);
    }
    
    public PCITC.MES.MM.CU.BLL.Entity.Interope.CuIopRetVal SaveInstrumentMeasure(PCITC.MES.MM.CU.BLL.Entity.InstrumentMeasureRec[] recList, PCITC.MES.MM.CU.BLL.Entity.UnitStateRec unitStateRec, System.DateTime shiftBeginTime, System.DateTime shiftEndTime, long unitId, string userId)
    {
        return base.Channel.SaveInstrumentMeasure(recList, unitStateRec, shiftBeginTime, shiftEndTime, unitId, userId);
    }
    
    public System.Threading.Tasks.Task<PCITC.MES.MM.CU.BLL.Entity.Interope.CuIopRetVal> SaveInstrumentMeasureAsync(PCITC.MES.MM.CU.BLL.Entity.InstrumentMeasureRec[] recList, PCITC.MES.MM.CU.BLL.Entity.UnitStateRec unitStateRec, System.DateTime shiftBeginTime, System.DateTime shiftEndTime, long unitId, string userId)
    {
        return base.Channel.SaveInstrumentMeasureAsync(recList, unitStateRec, shiftBeginTime, shiftEndTime, unitId, userId);
    }
    
    public bool QueryAndSaveInstrMeasure(long unitId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId)
    {
        return base.Channel.QueryAndSaveInstrMeasure(unitId, begShiftTime, endShiftTime, userId);
    }
    
    public System.Threading.Tasks.Task<bool> QueryAndSaveInstrMeasureAsync(long unitId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId)
    {
        return base.Channel.QueryAndSaveInstrMeasureAsync(unitId, begShiftTime, endShiftTime, userId);
    }
    
    public PCITC.MES.MM.CU.BLL.Entity.UnitTankMeasureRec[] GetTankMeasureRecs(PCITC.MES.MM.CU.BLL.Entity.UnitShiftTime ust)
    {
        return base.Channel.GetTankMeasureRecs(ust);
    }
    
    public System.Threading.Tasks.Task<PCITC.MES.MM.CU.BLL.Entity.UnitTankMeasureRec[]> GetTankMeasureRecsAsync(PCITC.MES.MM.CU.BLL.Entity.UnitShiftTime ust)
    {
        return base.Channel.GetTankMeasureRecsAsync(ust);
    }
    
    public PCITC.MES.MM.CU.BLL.Entity.Interope.CuIopRetVal SaveUnitTankMeasureRec(PCITC.MES.MM.CU.BLL.Entity.UnitTankMeasureRec[] lstUtmr, PCITC.MES.MM.CU.BLL.Entity.UnitStateRec unitStateRec, System.DateTime shiftBeginTime, System.DateTime shiftEndTime, long unitId, string userId)
    {
        return base.Channel.SaveUnitTankMeasureRec(lstUtmr, unitStateRec, shiftBeginTime, shiftEndTime, unitId, userId);
    }
    
    public System.Threading.Tasks.Task<PCITC.MES.MM.CU.BLL.Entity.Interope.CuIopRetVal> SaveUnitTankMeasureRecAsync(PCITC.MES.MM.CU.BLL.Entity.UnitTankMeasureRec[] lstUtmr, PCITC.MES.MM.CU.BLL.Entity.UnitStateRec unitStateRec, System.DateTime shiftBeginTime, System.DateTime shiftEndTime, long unitId, string userId)
    {
        return base.Channel.SaveUnitTankMeasureRecAsync(lstUtmr, unitStateRec, shiftBeginTime, shiftEndTime, unitId, userId);
    }
    
    public bool QueryAndSaveUnitTankRec(long unitId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId)
    {
        return base.Channel.QueryAndSaveUnitTankRec(unitId, begShiftTime, endShiftTime, userId);
    }
    
    public System.Threading.Tasks.Task<bool> QueryAndSaveUnitTankRecAsync(long unitId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId)
    {
        return base.Channel.QueryAndSaveUnitTankRecAsync(unitId, begShiftTime, endShiftTime, userId);
    }
    
    public PCITC.MES.MM.CU.BLL.Entity.UnitInOutRec[] ReCulcInOutRecs(PCITC.MES.MM.CU.BLL.Entity.UnitShiftTime ust)
    {
        return base.Channel.ReCulcInOutRecs(ust);
    }
    
    public System.Threading.Tasks.Task<PCITC.MES.MM.CU.BLL.Entity.UnitInOutRec[]> ReCulcInOutRecsAsync(PCITC.MES.MM.CU.BLL.Entity.UnitShiftTime ust)
    {
        return base.Channel.ReCulcInOutRecsAsync(ust);
    }
    
    public PCITC.MES.MM.CU.BLL.Entity.Interope.CuIopRetVal SaveInOutRec(PCITC.MES.MM.CU.BLL.Entity.UnitInOutRec[] listUior, System.DateTime shiftBeginTime, System.DateTime shiftEndTime, long unitId, string userId)
    {
        return base.Channel.SaveInOutRec(listUior, shiftBeginTime, shiftEndTime, unitId, userId);
    }
    
    public System.Threading.Tasks.Task<PCITC.MES.MM.CU.BLL.Entity.Interope.CuIopRetVal> SaveInOutRecAsync(PCITC.MES.MM.CU.BLL.Entity.UnitInOutRec[] listUior, System.DateTime shiftBeginTime, System.DateTime shiftEndTime, long unitId, string userId)
    {
        return base.Channel.SaveInOutRecAsync(listUior, shiftBeginTime, shiftEndTime, unitId, userId);
    }
    
    public bool RecAndSaveInOutPutRec(long unitId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId)
    {
        return base.Channel.RecAndSaveInOutPutRec(unitId, begShiftTime, endShiftTime, userId);
    }
    
    public System.Threading.Tasks.Task<bool> RecAndSaveInOutPutRecAsync(long unitId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId)
    {
        return base.Channel.RecAndSaveInOutPutRecAsync(unitId, begShiftTime, endShiftTime, userId);
    }
    
    public bool UnitSeal(long unitId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId)
    {
        return base.Channel.UnitSeal(unitId, begShiftTime, endShiftTime, userId);
    }
    
    public System.Threading.Tasks.Task<bool> UnitSealAsync(long unitId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId)
    {
        return base.Channel.UnitSealAsync(unitId, begShiftTime, endShiftTime, userId);
    }
    
    public bool UnitUnSeal(long unitId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId)
    {
        return base.Channel.UnitUnSeal(unitId, begShiftTime, endShiftTime, userId);
    }
    
    public System.Threading.Tasks.Task<bool> UnitUnSealAsync(long unitId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId)
    {
        return base.Channel.UnitUnSealAsync(unitId, begShiftTime, endShiftTime, userId);
    }
    
    public bool ShiftDataAutoCalcAndSeal(long unitId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId)
    {
        return base.Channel.ShiftDataAutoCalcAndSeal(unitId, begShiftTime, endShiftTime, userId);
    }
    
    public System.Threading.Tasks.Task<bool> ShiftDataAutoCalcAndSealAsync(long unitId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId)
    {
        return base.Channel.ShiftDataAutoCalcAndSealAsync(unitId, begShiftTime, endShiftTime, userId);
    }
    
    public bool QueryAndSaveMeaNodeInstrMeaSureMent(long nodeAreaId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId)
    {
        return base.Channel.QueryAndSaveMeaNodeInstrMeaSureMent(nodeAreaId, begShiftTime, endShiftTime, userId);
    }
    
    public System.Threading.Tasks.Task<bool> QueryAndSaveMeaNodeInstrMeaSureMentAsync(long nodeAreaId, System.DateTime begShiftTime, System.DateTime endShiftTime, string userId)
    {
        return base.Channel.QueryAndSaveMeaNodeInstrMeaSureMentAsync(nodeAreaId, begShiftTime, endShiftTime, userId);
    }
}
